spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost/finalexam?characterEncoding=utf-8
    password: 456111
    username: root
    freemarker:
        content-type: application/json
server:
  port: 3000
